config/routes.rb
Rails.application.routes.draw do
  resources :test_signups
  resources :drivers
  get 'home/index'

   root 'home#index'

end

app/models/driver.rb
class Driver < ActiveRecord::Base
end

app/models/test_signup.rb
class TestSignup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.fetch(:driver, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/test_signups_controller.rb
class TestSignupsController < ApplicationController
  before_action :set_test_signup, only: [:show, :edit, :update, :destroy]

  # GET /test_signups
  # GET /test_signups.json
  def index
    @test_signups = TestSignup.all
  end

  # GET /test_signups/1
  # GET /test_signups/1.json
  def show
  end

  # GET /test_signups/new
  def new
    @test_signup = TestSignup.new
  end

  # GET /test_signups/1/edit
  def edit
  end

  # POST /test_signups
  # POST /test_signups.json
  def create
    @test_signup = TestSignup.new(test_signup_params)

    respond_to do |format|
      if @test_signup.save
        format.html { redirect_to @test_signup, notice: 'Test signup was successfully created.' }
        format.json { render :show, status: :created, location: @test_signup }
      else
        format.html { render :new }
        format.json { render json: @test_signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_signups/1
  # PATCH/PUT /test_signups/1.json
  def update
    respond_to do |format|
      if @test_signup.update(test_signup_params)
        format.html { redirect_to @test_signup, notice: 'Test signup was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_signup }
      else
        format.html { render :edit }
        format.json { render json: @test_signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_signups/1
  # DELETE /test_signups/1.json
  def destroy
    @test_signup.destroy
    respond_to do |format|
      format.html { redirect_to test_signups_url, notice: 'Test signup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_signup
      @test_signup = TestSignup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_signup_params
      params.fetch(:test_signup, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/test_signups_helper.rb
module TestSignupsHelper
end

app/views/drivers/_form.html.erb
<%= form_for(@driver) do |f| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% @driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form' %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form' %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

app/views/home/index.html.erb
<div id="homepage">
	<!--<div class="loader-screen">
	<div class="loader"></div>
	</div>-->
	<!-- <div class="loader-screen">
		<div class="loader-ball-scale">
			<div></div>
		</div>
	</div> -->
	<div id="skrollr-body">

		<section id="hp-section1">
			<div class="products middle skrollable skrollable-between" data-0="transform:translate3d(-50%, -50%, 0); opacity:1;" data-top="transform:translate3d(-50%, -10%, 0); opacity:0;">
				<header itemscope itemtype="http://schema.org/WPHeader">
					<div class="title1" style="font-size: 70px">
						Be In Control
					</div>
					<div class="title2" style="font-size: 25px">
						<!-- The UK's black cab app -->
					</div>

				</header>
				<div class="section1-download"></div>
				<ul class="apps">
					<li>
						<a href="" target="_blank" class="btn-app btn-border"> <i class="icon icon-btn-appstore"></i> </a>
					</li>
					<li>
						<a href="" target="_blank" class="btn-app btn-border"> <i class="icon icon-btn-playstore"></i> </a>
					</li>
				</ul>
			</div>
			<a href="" class="btn-scroll-down skrollable skrollable-between" data-0="opacity:1" data-400-top="opacity:0"></a>

			<!-- <div class="section1-video video-container" >
			<div class="black-mask"></div>
			</div> -->

			<div class="section1-video video-container" style="background-image: url(/assets/airport_logo.jpg);">
				<div class="black-mask"></div>
			</div>
		</section>

		<section id="ride">
			<div class="section2-1"
			data-0="transform:translate3d(-30%, 0, 0); opacity:0;"
			data-400-top="transform:translate3d(0%, 0, 0); opacity:1;"
			data-bottom="transform:translate3d(0%, 0, 0); opacity:1;"
			data--1000-bottom="transform:translate3d(-30%, 0, 0); opacity:0;">
				<img itemprop="image" src="/assets/Website_iphone_may20188.png/" alt="" class="phone">
				<%#= image_tag "/assets/Website_iphone_may20188.png/", class: "phone" ,itemprop: "image"%>

			</div>
			<div class="section2-2 skrollable skrollable-between"
			data-0="transform:translate3d(30%, 0, 0); opacity:0;"
			data-400-top="transform:translate3d(0%, 0, 0); opacity:1;"
			data-bottom="transform:translate3d(0%, 0, 0); opacity:1;"
			data--1000-bottom="transform:translate3d(30%, 0, 0); opacity:0;">
				<div class="middle">
					<div class="items">
						<div class="item">
							<h2>Why Dropping?</h2>
						</div>

						<div class="item">
							<ul id="items" class="cf">

								<li class="iconContent span33 alignleft">
									<div class="icon">
										<div class="icon-bg">
											<div class="arc"></div>
										</div>
										<!-- <img itemprop="image" src="https://gett.com/uk/wp-content/uploads/sites/6/2015/11/best_rated_UK.png"
										alt=""/> -->
										<img itemprop="image" src="/assets/medal.png">
									</div>
									<div class="iconText">
										No more hassling or hailing  for a ride, use Dropping<sup>SM</sup>
									</div>
									<div class="iconSubtext">
										<!-- Ride with UK's highest rated drivers -->
									</div>
								</li>
								<li class="iconContent span33 alignleft">
									<div class="icon">
										<div class="icon-bg">
											<div class="arc"></div>
										</div>
										<!-- <img itemprop="image" src="https://gett.com/uk/wp-content/uploads/sites/6/2017/04/2.png"
										alt=""/> -->
										<img itemprop="image" src="/assets/order.png"
										alt=""/>

									</div>
									<div class="iconText">
										Book for Now, Later., Other and Airport pickup.
									</div>
									<div class="iconSubtext">
										<!-- Arrive 3 minutes quicker than Uber
										<br />
										*Loudhouse 2017 -->
									</div>
								</li>
								<li class="iconContent span33 alignleft">
									<div class="icon">
										<div class="icon-bg">
											<div class="arc"></div>
										</div>
										<!-- <img itemprop="image" src="https://gett.com/uk/wp-content/uploads/sites/6/2016/02/receiving.png"
										alt=""/> -->
										<img itemprop="image" src="/assets/option.png">
									</div>
									<div class="iconText">
										Option to choose the best rated drivers, for all your rides.
									</div>
									<div class="iconSubtext">
										<!-- The smart way to order a black cab -->
									</div>
								</li>
								<li class="iconContent span33 alignleft">
									<div class="icon">
										<div class="icon-bg">
											<div class="arc"></div>
										</div>
										<!-- <img itemprop="image" src="https://gett.com/uk/wp-content/uploads/sites/6/2015/11/BEST_FARES_UK.png"
										alt=""/> -->
										<img itemprop="image" src="/assets/currency.png">
									</div>
									<div class="iconText">
										Never pay for surge pricing again.
									</div>
									<div class="iconSubtext">
										<!-- Know your fare
										<br />
										before you order -->
									</div>
								</li>
								<li class="iconContent span33 alignleft">
									<div class="icon">
										<div class="icon-bg">
											<div class="arc"></div>
										</div>
										<!-- <img itemprop="image" src="https://gett.com/uk/wp-content/uploads/sites/6/2015/11/hp-icon-clock.png"
										alt=""/> -->
										<!-- <img itemprop="image" src="https://gett.com/uk/wp-content/uploads/sites/6/2015/11/hp-icon-gift.png"
										alt=""/>  -->
										<img itemprop="image" src="/assets/gift.png">

									</div>
									<div class="iconText">
										Redeem your reward points per each ride.
									</div>
									<!-- <div class="iconSubtext">
									Gett a black cab asap
									<br>
									or pre-book in advance.
									</div> -->
								</li>
								<li class="iconContent span33 alignleft">
									<div class="icon">
										<div class="icon-bg">
											<div class="arc"></div>
										</div>
										<!-- <img itemprop="image" src="https://gett.com/uk/wp-content/uploads/sites/6/2015/11/hp-icon-gift.png"
										alt=""/> -->
										<!-- <img itemprop="image" src="https://gett.com/uk/wp-content/uploads/sites/6/2017/04/2.png"
										alt=""/>  -->
										<img itemprop="image" src="/assets/watch.png">
									</div>
									<div class="iconText">
										Wait time is over, no more standing in line for a taxi/trotro.
									</div>
									<div class="iconSubtext">
										<!-- Share the Gett app with your friends and earn free rides. -->
									</div>
								</li>

							</ul>
						</div>

					</div>
				</div>
			</div>
		</section>
	</div>

	<section
	id="section-raw-php-user-education-body"
	class="section section--light section-raw-php bg-size-cover"
style="background-color:#fbb417";												padding-top: 0px;padding-bottom: 0px;">
		<div class="container-fluid">

			<header></header>

			<style>
.step1 .fluid-container {padding-top:90px; padding-bottom:85px}
.step1 h2 {font-weight: lighter; font-size: 2.571em; color: #101010; text-align: center; width:100%; max-width:620px;margin-left:auto; margin-right:auto; margin-bottom:50px; padding-left:15px; padding-right:15px;}
.step1 .btn {background-color:#fff; color:#101010; text-transform:uppercase; border-radius: 0; box-shadow: none; padding: 16px 20px 15px; font-size: 1.35em; line-height: 1;}
			</style>
			<div class="step1">
				<div class="row">
					<div class="fluid-container text-center" style="background-color:#fbb417">
						<h2>What you should know before your first Dropping ride</h2>
						<a href="" class="btn btnNext">click to learn</a>
					</div>
				</div>
			</div>

		</div>
	</section>





		<section
		id="section-carousel-tooltip-homepage-services"
		class="section section-carousel-tooltip section--dark">

			<header>
				<!-- <h2>Rides For Everyone</h2> -->
			</header>
			<div class="carousel carousel-tooltip carousel-fade slide" data-ride="carousel" id="carousel-homepage-services">
				<ol class="carousel-indicators">
					<li class="active" data-slide-to="0" data-target="#carousel-homepage-services">
						<i class="icon icon--hover icon--service--taxi"></i>
					</li>
					<li data-slide-to="1" data-target="#carousel-homepage-services">
						<i class="icon icon--hover icon--service--car"></i>
					</li>

				</ol>
				<div class="carousel-inner" role="listbox">
					<div class="item item-1 bg-size-cover active" style="background-image: url(/assets/taxi_girl.jpg);">
						<div class="carousel-caption">
							<h1>Taxi</h1>
							<p>
								More taxis than any other app in Ghana, at your service.
							</p>
							<a href="taxi"><span></span></a>
						</div>
					</div>
					<div class="item item-2 bg-size-cover" style="background-image: url(/assets/private_girl.jpg);">
						<div class="carousel-caption">
							<h1>Private Car</h1>
							<p>
								A car for every need, from everyday cars to luxury vehicles.
							</p>
							<a href="car"><span></span></a>
						</div>
					</div>

				</div><!-- /carousel-inner -->
			</div><!-- /carousel -->
		</section>

		<div id="skrollr-body">
			<section id="hp-section6">
				<!-- <div class="loader-inner ball-scale">
				<div></div>
				</div> -->
				<div class="section6-1 align">
					<div class="middle">
						<div class="title">
							Be In Control
						</div>
						<div class="text">
							Watch Kofi’s video on how he was recruited
						</div>
					</div>
				</div>
				<div class="section6-2">
					<div class="video">
						<img itemprop="image" src="/assets/testi.jpg" alt=""/>
						<a href="" class="btn-play" data-video="2rbWvi8zj6I"></a>
					</div>
				</div>
			</section>
		</div>
</div>

<div class="lb video">
	<div id="gett-video"></div>
	<a href="" class="btn-close"></a>
</div>


app/views/test_signups/_form.html.erb
<%= form_for(@test_signup) do |f| %>
  <% if @test_signup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_signup.errors.count, "error") %> prohibited this test_signup from being saved:</h2>

      <ul>
      <% @test_signup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_signups/edit.html.erb
<h1>Editing Test Signup</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_signup %> |
<%= link_to 'Back', test_signups_path %>

app/views/test_signups/new.html.erb
<h1>New Test Signup</h1>

<%= render 'form' %>

<%= link_to 'Back', test_signups_path %>

app/views/test_signups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_test_signup_path(@test_signup) %> |
<%= link_to 'Back', test_signups_path %>